### ISSUE TITLE
Does data pull from other repo work?

### ISSUE THREAD

**Issue by colebrookson** [katherinehebert/dfo_INLA#2]
Heya, wondering if you can actually access the data from the private repo through the `read_in_all_data.R` script? You should have access to to the repo but I can resend if useful, just wanted to see if that method was actually working on your end? I can also re-jig the way all the data get read in if there's a cleaner way to keep just the data private across all users on the repo?

**Comment by katherinehebert** [comment]
Hey amazing timing, I actually ran into this issue during the last models but thought it might just be me. I however don't have the private data repo from cloning this, so I think I would have to just recreate the folder on my end (unless you can think of another way of doing this!)

**Comment by colebrookson** [comment]
Hmm gotchu. This might be worth a super quick call at some point, and I can show you how I *think* it could work, and you can tell me if that is a terrible idea or not?

**Comment by katherinehebert** [comment]
sounds good!! :)
